Add base layout
subvisual/desktop pull request #2
Opened 2024-04-22 08:51 UTC by davelange

Why:
 - New layout has a sidebar nav wrapping all pages except Onboarding

How
 - Add a BaseLayout and Sidebar components that wrap the pages content. Not styled yet.
 - Move the wallet widget and behaviour in to the BaseLayout, as it will be present on all these pages.

2024-04-23 15:39 UTC, davelange commented
@juliangruber while the other PRs are pending, I prepared this one to setup the new app layout structure.

2024-04-23 19:39 UTC, juliangruber requested changes
Nice! I've pinged Miro on Slack about these reviews

2024-04-23 19:39 UTC, juliangruber commented on renderer/src/App.tsx
> +import BaseLayout from 'src/components/BaseLayout'
can we call this `Layout` instead?

2024-04-24 10:07 UTC, juliangruber commented
could you please recreate this PR on the main repo?

2024-04-26 08:50 UTC, closed without merging